### ISSUE TITLE
only display red borders

### ISSUE THREAD

**Issue by adammhl** [rumax/react-native-PDFView#104]
only render red borders in my project, my rn version is 0.45.1, can you tell me how to fix it. thank you very much.

**Comment by rumax** [comment]
Hi @adammhl ,

Can you please provide more information? Can you also reproduce it in the [demo](https://github.com/rumax/react-native-PDFView/tree/master/demo) project?

**Comment by adammhl** [comment]
thank you，we should import your lib to our root project
