### ISSUE TITLE
Invariant Violation: requireNativeComponent: "PDFView" was not found in the UIManager.

### ISSUE THREAD

**Issue by telltokichu** [rumax/react-native-PDFView#108]
Getting this error 
"ExceptionsManager.js:74 Invariant Violation: requireNativeComponent: "PDFView" was not found in the UIManager."

any solution?

**Comment by rumax** [comment]
Hi @telltokichu , thank you for trying the project. 

Can you, please, follow the bug template when you create the issues? 

Unfortunately with the information provided, I will not be able to help. I even do not now which version was used. 

As an alternative, you can also provide a link to your project and I can try to run it when I have some free time.

**Comment by ansarikhurshid786** [comment]
I am also getting same error  in iphone x

**Comment by rumax** [comment]
> I am also getting same error in iphone x 

Only `iphone x`?

**Comment by sanderfrenken** [comment]
Sounds like a linking problem. Can you check if the framework is linked properly in your project?
In addition, please confirm the demo project is able to run on iPhoneX. If so, your project setup is most likely the culprit of this issue.

**Comment by AleMeritano** [comment]
I'm getting the same error on every android emulator.

Those are my dependencies
`"dependencies": {
    "@react-native-community/async-storage": "^1.6.1",
    "moment": "2.19.0",
    "prop-types": "^15.5.10",
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-checkbox": "^1.2.0",
    "react-native-datepicker": "^1.6.0",
    "react-native-fa-icons": "^3.0.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-global-props": "^1.1.1",
    "react-native-phone-call": "^1.0.4",
    "react-native-router-flux": "^4.0.0-beta.21",
    "react-native-view-pdf": "^0.9.1",
    "react-native-viewport-units": "0.0.5",
    "react-navigation": "^1.0.0-beta.11",
    "render-if": "^0.1.1"
  },`

I've tried without linking (react-native > 0.60), with react-native link react-native-view-pdf and even with manual linking. When i navigate to my component that should render the pdf I get "Invariant Violation: requireNativeComponent: "PDFView" was not found in the UIManager".

Here is my component using the library:

`import React, { Component } from 'react';
import { StyleSheet, Dimensions, View, Text } from 'react-native';
import Icon from 'react-native-fa-icons';
import PDFView from 'react-native-view-pdf';

export default class PDF extends Component {

    static navigationOptions = ({navigation}) => ({
        headerTitle: navigation.state.params.documentName.toUpperCase(),
        headerLeft: <Text style={{marginLeft: GLOBAL.styles.margins.m}} onPress={() => { navigation.goBack() }}>
            <Icon name='chevron-left' style={{fontSize: GLOBAL.styles.fontSizes.m, color: GLOBAL.styles.colors.colorTwo,}} />
        </Text>
    });

    constructor(props) {
        super(props);

        this.state = {
            documentUrl: this.props.navigation.state.params.documentUrl,
        }
    }

    render() {
        const source = {uri:this.state.documentUrl};
        const resourceType = "url";

        return (
            <View style={styles.container}>
                <PDFView
                    fadeInDuration={250.0}
                    style={{ flex: 1 }}
                    resource={source}
                    resourceType={resourceType}
                    onError={() => console.log('Cannot render PDF', error)}
                />
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'flex-start',
        alignItems: 'center',
        marginTop: 25,
    }
});`

**Comment by dellwatson** [comment]
Still occurs using EXPO sdk 34, on iOS across all devices have the same problem 'PDFView was not found in UIManager', not sure about android.

**Comment by ihranova** [comment]
I have still the same occurs with OS devices.

**Comment by eyalabadi98** [comment]
Any updates, I get the same issue

**Comment by rumax** [comment]
Hi @eyalabadi98 , what kind of updates do you expect? 

If you face the same issue, you can try to reproduce it in the [demo project](https://github.com/rumax/react-native-PDFView/tree/master/demo) and give more details about the issue, as it was asked above.

All sources are also opened, and if during debugging you find an issue, you are welcome to create a [PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests) with the fix

**Comment by mynameisthunder** [comment]
any updates on this? i have the same issue - not using expo though

**Comment by peterone1998** [comment]
i get the same issue with android. react native version 0.61

**Comment by rumax** [comment]
> i get the same issue with android. react native version 0.61

@peterone1998 can you share you project, so that I can check?

**Comment by Keaws** [comment]
Getting the same error on android version 9.0+

`Invariant Violation: requireNativeComponent: "PDFView" was not found in the UIManager.
- node_modules/react-native/Libraries/ReactNative/getNativeComponentAttributes.js:29:4 in getNativeComponentAttributes
- node_modules/react-native/Libraries/Renderer/shims/ReactNativeViewConfigRegistry.js:104:25 in get
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:3988:53 in createInstance
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:14437:12 in completeWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17094:10 in completeUnitOfWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17304:30 in performUnitOfWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17316:41 in workLoop
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17417:15 in renderRoot
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18423:17 in performWorkOnRoot
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18324:24 in performWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18285:14 in performSyncWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18169:19 in requestWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17969:16 in scheduleWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18642:15 in scheduleRootUpdate
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:19512:20 in render
- node_modules/react-native/Libraries/ReactNative/renderApplication.js:61:34 in renderApplication
- node_modules/react-native/Libraries/ReactNative/AppRegistry.js:104:10 in run
- node_modules/react-native/Libraries/ReactNative/AppRegistry.js:198:26 in runApplication
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:366:47 in __callFunction
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:106:26 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:314:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:105:17 in callFunctionReturnFlushedQueue
* [native code]:null in callFunctionReturnFlushedQueue`

Here is sample repository to reproduce:
https://github.com/Keaws/sample-react-native

@rumax Could you check on your end please?

**Comment by rumax** [comment]
> Getting the same error on android version 9.0+
> 
> `Invariant Violation: requireNativeComponent: "PDFView" was not found in the UIManager.
> 
>     * node_modules/react-native/Libraries/ReactNative/getNativeComponentAttributes.js:29:4 in getNativeComponentAttributes
> 
>     * node_modules/react-native/Libraries/Renderer/shims/ReactNativeViewConfigRegistry.js:104:25 in get
> 
>     * node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:3988:53 in createInstance
> 
>     * node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:14437:12 in completeWork
> 
>     * node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17094:10 in completeUnitOfWork
> 
>     * node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17304:30 in performUnitOfWork
> 
>     * node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17316:41 in workLoop
> 
>     * node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17417:15 in renderRoot
> 
>     * node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18423:17 in performWorkOnRoot
> 
>     * node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18324:24 in performWork
> 
>     * node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18285:14 in performSyncWork
> 
>     * node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18169:19 in requestWork
> 
>     * node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17969:16 in scheduleWork
> 
>     * node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18642:15 in scheduleRootUpdate
> 
>     * node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:19512:20 in render
> 
>     * node_modules/react-native/Libraries/ReactNative/renderApplication.js:61:34 in renderApplication
> 
>     * node_modules/react-native/Libraries/ReactNative/AppRegistry.js:104:10 in run
> 
>     * node_modules/react-native/Libraries/ReactNative/AppRegistry.js:198:26 in runApplication
> 
>     * node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:366:47 in __callFunction
> 
>     * node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:106:26 in
> 
>     * node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:314:10 in __guard
> 
>     * node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:105:17 in callFunctionReturnFlushedQueue
> 
> 
>     * [native code]:null in callFunctionReturnFlushedQueue`
> 
> 
> Here is sample repository to reproduce:
> https://github.com/Keaws/sample-react-native
> 
> @rumax Could you check on your end please?

<img width="982" alt="Screenshot 2019-12-02 at 20 04 31" src="https://user-images.githubusercontent.com/2707180/69987113-0e952600-153f-11ea-903a-b676f0ac27e0.png">

No issues after fixing style and `onLoad` callback

**Comment by Keaws** [comment]
@rumax I just found that starting project with `react-native start` works fine, but when I use `expo start` then error appears. Any chance you may know what's going on?
