### ISSUE TITLE
Unable to load the PDF file from iOS device

### ISSUE THREAD

**Issue by deepak28** [rumax/react-native-PDFView#112]
Great workaround from yourside, just getting the **PDF File not found** when running in iOS device/simulator.

Although its working absolutely fine in Android.

Please suggest your valuable instructions.

**Comment by rumax** [comment]
@deepak28 Thank you for using the project. Would you be so kind to fill the template and provide more information? Are you taking about demo project or your project?

**Comment by deepak28** [comment]
I am talking about my project, i've just debugging in native code.
```

 NSString *filePath = [documentsDirectory stringByAppendingPathComponent: _resource];
    if(![[NSFileManager defaultManager] fileExistsAtPath: filePath]) {
        return nil;
    }
```

This is returning `nil` even in case of file exists.

This is my attachmentURL - /Users/admin/Library/Developer/CoreSimulator/Devices/651BE5C4-C627-4DFF-A6AA-57D7DF9BDFF1/data/Containers/Data/Application/D53396CA-5B61-4589-86FB-992987950580/Documents/Users/admin/Library/Developer/CoreSimulator/Devices/651BE5C4-C627-4DFF-A6AA-57D7DF9BDFF1/data/Containers/Data/Application/D53396CA-5B61-4589-86FB-992987950580/Documents/sbsdk-temp/38E289CA-B17A-4F6A-B4C3-E20E09657717.pdf

Which is not loading on <PDFView/>.

Here is my code snippet - 


    const resources = {
      file: attachmentURL
    };
    const resourceType = 'file';
<PDFView
                            fadeInDuration={250.0}
                            style={{width: avatarWidth, height: avatarHeight}}
                            resource={resources[resourceType]}
                            resourceType={resourceType}
                            onLoad={() => console.log(`PDF rendered from ${resourceType}`)}
                            onError={(error) =>
                              alert('Cannot render PDF 3' +  JSON.stringify(error) +  resources[resourceType])
                            }
                          />

@rumax - Can you please help me on this, i have already spent 2 days on this.

**Comment by rumax** [comment]
Hi @deepak28 Maybe you can try the demo project and reproduce the issue in it? In this case if I have clear steps, I will be able to also reproduce it, debug and fix the issue if it exists. 

From the information you showed I can only understand that you get `nil` which means that the path can be wrong, or file name, etc. Not sure how I can help you with this.

**Comment by humphreyja** [comment]
Just going to make a note for anyone who is running into this issue.  I had to pass the RELATIVE path to the component (not the full path that you may get back from rn-fetch-blob).  The easiest way to do this is just;
```js
const file = '/Users/admin/Library/Developer/CoreSimulator/Devices/651BE5C4-C627-4DFF-A6AA-57D7DF9BDFF1/data/Containers/Data/Application/D53396CA-5B61-4589-86FB-992987950580/Documents/sbsdk-temp/38E289CA-B17A-4F6A-B4C3-E20E09657717.pdf'

const resources = {
  file: file.replace(/.*\/Documents\//, '');
};
const resourceType = 'file';
```
