### ISSUE TITLE
0.59 support?

### ISSUE THREAD

**Issue by sam17896** [rumax/react-native-PDFView#121]
i am getting following error after upgrading my project to version 0.59 of react native.

```
* What went wrong:
Could not resolve all files for configuration ':react-native-view-pdf:debugCompileClasspath'.
> Could not resolve com.android.support:support-compat:25.3.1.
  Required by:
      project :react-native-view-pdf
```

Does this package supports the latest version of react-native?

**Comment by rumax** [comment]
Hi @sam17896, at first glance it should, do not see anything wrong. Moreover, I've tried the [demo project](https://github.com/rumax/react-native-PDFView/tree/master/demo) and didn't get any issues.

https://github.com/rumax/react-native-PDFView/pull/122
