### ISSUE TITLE
Load Initial Page

### ISSUE THREAD

**Issue by daveyleo** [rumax/react-native-PDFView#126]
**Is your feature request related to a problem? Please describe.**
I have a specific link/button in my app that I want to open a PDF and have it initially display a specific page number in the PDF.

**Describe the solution you'd like**
 <PDFView
            initialPage={20}
            resource = {source}
            resourceType = {"file"} />

**Comment by rumax** [comment]
Hi @daveyleo, thank you for using the PDF viewer and requesting a feature. It sounds like a really good addition! Meantime our idea of the viewer was to make it simple, with basic functionality and well maintained. And unfortunately it will be hard to find some free time to implement this feature for me now. But if you have some time and would like to contribute, will it be possible to create a Pull Request with the implementation of this feature?
