### ISSUE TITLE
Add support for credentials

### ISSUE THREAD

**Issue by mgcrea** [rumax/react-native-PDFView#127]
**Is your feature request related to a problem? Please describe.**

I'm trying to fetch a PDF that relies on a cookie-based authentification

**Describe the solution you'd like**

Adding support for a `credentials` option that mimick the related [fetch option](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Sending_a_request_with_credentials_included).

Maybe in urlProps?

**Comment by YKSing** [comment]
And also `Authorization` in header too.
