### ISSUE TITLE
Support for AndroidX

### ISSUE THREAD

**Issue by cassioseffrin** [rumax/react-native-PDFView#128]
**Is your feature request related to a problem? Please describe.**
Support for AndroidX. Here is some breaking changes: https://facebook.github.io/react-native/blog/2019/07/03/version-60

 
**Additional context**
Here a starting point for this migration process: https://react-native-community.github.io/upgrade-helper/

**Comment by rumax** [comment]
Hi @cassioseffrin , new version `0.9.0` which support rn 0.60.0 is published.  [Demo project](https://github.com/rumax/react-native-PDFView/tree/master/demo) is also upgraded to rn `0.60.0`. Can you, please, check if this version works for you, including AndroidX. And if not specify the issues in more details, so that I can fix it.

**Comment by cassioseffrin** [comment]
thks @rumax, Very fast and now it's 100% compatible with RN0.60.  I will close this issue.

 I only have a small question about the pdf encoding on iOS. My PDFs use accents (latin1 encode) and are generated on the server side and transferred to the app in base64. Only in iOS I can not understand why the accents aren't right, in android they are fine.  I will really appreciate if you have some clue about the correct encoding, I tried to change it to latin1 in xcode but I have no effect.

**Comment by rumax** [comment]
@cassioseffrin thanks for confirmation. 

Regarding the encoding, is it in your project or also demo project? If it is also demo project will be be possible for you to provide some examples of such PDFs?

**Comment by cassioseffrin** [comment]
@rumax thks in advance for your attention.

Here is the pdf sample that have accents issue only in iOS:
https://wetransfer.com/downloads/a84782765d18751d59a149dfb508975b20190715123001/6e21e41e5eb24788322816660d750eb720190715123001/aecdc3

If you open it in browser or pdf viewer it's ok, the issue happen only details lines for iOS.
12938 TILÁPIA FRITA 1 UN X 15,000 15,00 (correct android)
12938 TIL(encoding issue happens here)PIA FRITA 1 UN X 15,000 15,00 (incorrect iOs)

**Comment by cassioseffrin** [comment]
any update?

**Comment by sanderfrenken** [comment]
@cassioseffrin unfortunately not yet. I just now took a quick look, but if I understand correctly you pass your pdf as base64 data to `PDFView`, correct?

Then the first thing I can quickly think you of you could try is to change L101 in `PDFView` from:
```
NSString *characterEncodingName = [_textEncoding isEqual: UTF_16] ? UTF_16 : UTF_8;
```
to:
```
```
NSString *characterEncodingName = @"latin-1";
```
Did you try that already?

**Comment by rumax** [comment]
Please, check version `0.10.0` for AndroidX

**Comment by cassioseffrin** [comment]
@sanderfrenken I have tried to change it to Latin1 but no effect.

Anyway thks for help!
