### ISSUE TITLE
Not Ready For Android X

### ISSUE THREAD

**Issue by geoc3** [rumax/react-native-PDFView#131]
Do you have a work around for those not ready to go to Android X? We just started using your library but aren't ready to make the jump just yet and have to get some builds out next week.

**Comment by rumax** [comment]
Is you issue different to #128 ? Can you, please, specify more details?

**Comment by geoc3** [comment]
Hi yes was wondering if there was a way to use the library without supporting Android X we aren't ready to make the conversion yet but once you flip the Android X switch on one library you have to do it for the whole app. Was wondering if there is a way for backwards compatibility with react native versions less the 60. Or should I just install an earlier version.

**Comment by rumax** [comment]
I have no idea which RN version do you use, but let's say if you have RN 0.59, I do not see any issues that you can face with version `0.9.0`.

**Comment by geoc3** [comment]
We are using .59 we will give a whirl and see what happens if all else fails we can just do the previous version. Thanks! Still trying to get head wrapped around Android X

**Comment by rumax** [comment]
Please, check version `0.10.0` for AndroidX
