### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by kishansbs** [rumax/react-native-PDFView#134]
No pagination.
Please add it, or if possible how can i set it.
its required for my project,  
Thanks

**Comment by sanderfrenken** [comment]
Related to: https://github.com/rumax/react-native-PDFView/issues/113

Currently we have no plans to fully support pagination on iOS.
On Android you can already make use of the `onPageChanged` callback.

You are always more than welcome ofc to create a PR to create support for `onPageChanged` on iOS as well!
