### ISSUE TITLE
Unable to make it work on Android

### ISSUE THREAD

**Issue by sumit1317** [rumax/react-native-PDFView#142]
With "react-native": "0.60.4", I am able to make it work on iOS, but NOT able to make it work on Android (even after following config settings here https://github.com/rumax/react-native-PDFView#android

**Comment by rumax** [comment]
Hi @sumit1317, the [demo](https://github.com/rumax/react-native-PDFView/tree/master/demo) project uses ["react-native": "0.60.5"](https://github.com/rumax/react-native-PDFView/blob/b4e176386d36d6ff0cad426ca0a05fcb3a8585dc/demo/package.json#L12), so it should work. Maybe you can check and compare configuration to find out the issue and report it with more details?

**Comment by sumit1317** [comment]
This is how I am using it with "react-native": "0.60.4",

1. npm install react-native-view-pdf --save

2. cd ios

3. pod install

No other configs/file changes for ios or android.

It shows up the pdf in iOS, but does'nt show it on android (not even the
error)

 <PDFView
          fadeInDuration={250.0}
          style={{ flex: 1 }}
          resource={resources[resourceType]}
          resourceType={resourceType}
          onLoad={() => {
            this.setState({
              showSpinner: false,
              message: "Pdf loaded successfully."
            });
          }}
          onError={() => {
            this.setState({
              showSpinner: false,
              message: "Error loading pdf, try again."
            });
          }}
        />
Regards,
*Sumit S Chadha*

**Comment by rumax** [comment]
These are exactly the steps I do every time I upgrade RN and when I check the `demo` project. But I didn't get such issue. The best option would be if you reproduce it in `demo` project. Or try to debug to check what happens. PR is welcome if you find the issue.
