### ISSUE TITLE
[Q] How to show page break / page number in Android?

### ISSUE THREAD

**Issue by anniewey** [rumax/react-native-PDFView#144]
Pages are connected without page break that indicates new pages

**Comment by rumax** [comment]
For showing page break you can apply background color for the viewer like in demo project. Check this change https://github.com/rumax/react-native-PDFView/commit/b12dfa601dac616f885679fb702d25d46a1e50d2

<img width="308" alt="Screenshot 2019-10-02 at 09 28 22" src="https://user-images.githubusercontent.com/2707180/66025536-0268fa00-e4f7-11e9-8aeb-e27f473573fb.png">

Regarding `page number` you can check the https://github.com/barteksc/AndroidPdfViewer. If it is possible you can create a PR with an implementation.

**Comment by anniewey** [comment]
Ah, that's great. Thanks for the workaround!
