### ISSUE TITLE
Compatibility with doc and ppt files

### ISSUE THREAD

**Issue by JeremyBradshaw7** [rumax/react-native-PDFView#148]
I have tried this library and it works very well. On iOS I've found it even works for doc and ppt files, but on Android it doesn't. Can anything be done about this?

**Comment by rumax** [comment]
ios uses [WKWebView](https://developer.apple.com/documentation/webkit/wkwebview) and that's the reason why it is more than a pdf. And android implemented with [Android PdfViewer](https://github.com/barteksc/AndroidPdfViewer) which means only PDF. If you know a better library for android, please, let me know, I'll check it.

**Comment by JeremyBradshaw7** [comment]
> ios uses [WKWebView](https://developer.apple.com/documentation/webkit/wkwebview) and that's the reason why it is more than a pdf. And android implemented with [Android PdfViewer](https://github.com/barteksc/AndroidPdfViewer) which means only PDF. If you know a better library for android, please, let me know, I'll check it.

Yeah I realised that after reading the docs further. It was an unexpected bonus on iOS, and I suppose the library does what it was intended to do, it's not a generic viewer.
