### ISSUE TITLE
PDF background for differents Platforms/versions

### ISSUE THREAD

**Issue by PauloMello99** [rumax/react-native-PDFView#149]
*Android*: The background of the pdf content in android is white
*iOS*: Depending on the version of the iOS, the background is either black or gray
- Question:  Could be possible set a default background or even be able to change them?

**Comment by rumax** [comment]
Hi @PauloMello99, you are right it is different, but it was accepted for us, because these are different platforms and to fix it, it requires time and effort and we have lack of it now. But if you know how to fix it, you can also create a Pull Request. This would be nice!
