### ISSUE TITLE
Reload PDF when change height of View parent wrap PDF

### ISSUE THREAD

**Issue by dungnguyentri3110** [rumax/react-native-PDFView#150]
**Describe the bug**
I had problem of my project. When i change the height of View Parent wrap PDF, the PDF reload again. I dont know why.

**Comment by rumax** [comment]
Hi @dungnguyentri3110 , the best way to understand what is going on is to debug the app. You can also check these lines:

- https://github.com/rumax/react-native-PDFView/blob/master/android/src/main/java/com/rumax/reactnative/pdfviewer/PDFView.java#L188
- https://github.com/rumax/react-native-PDFView/blob/master/ReactNativeViewPDF/RNPDFView.m#L67

If you find it is the viewer issue, please, post detailed comments or create a pull request.

Or you can also try to reproduce it with the demo project https://github.com/rumax/react-native-PDFView/tree/master/demo
