### ISSUE TITLE
Scroll bar is getting displaying at the middle of the screen in iphoneX

### ISSUE THREAD

**Issue by SrikaraBhat** [rumax/react-native-PDFView#151]
As you can see in the image attached, there a vertical scrollbar is getting displaying. It is working fine in android and all IOS devices except IphoneX.

**Expected behavior**
Scrollbar should be avoided

**Screenshots**
Check in the attachment
![Screenshot 2020-01-06 at 7 11 34 PM](https://user-images.githubusercontent.com/48508148/71822957-35a1c300-30bc-11ea-9c25-acf3a240400e.jpg)

**Smartphone**
 - Device: iPhoneX
 - OS: iOS
 - Version 13.3.1

**Comment by rumax** [comment]
Hi @SrikaraBhat I've checked the [demo project](https://github.com/rumax/react-native-PDFView/tree/master/demo) but couldn't reproduce the issue. Can you, please, try to reproduce it there? Maybe some styling issues.

In this case we will have more information about the bug, so that we can fix it if it is in the viewer.

**Comment by SrikaraBhat** [comment]
> Hi @SrikaraBhat I've checked the [demo project](https://github.com/rumax/react-native-PDFView/tree/master/demo) but couldn't reproduce the issue.
> 
> <img alt="Screenshot 2020-01-08 at 19 10 19" width="368" src="https://user-images.githubusercontent.com/2707180/72003872-97903300-324a-11ea-84f8-0878d4544895.png">
> 
> Can you, please, try to reproduce it there? Maybe some styling issues.
> 
> In this case we will have more information about the bug, so that we can fix it if it is in the viewer.

This is observed only in iphoneX. For remaining devices it works fine. 

Reference code: 

<View
          style={commonStyles.roundedStripViewContainer}
          backgroundColor={Colors.white}>
          {isInvalid && this.rendeInvaildPdsMessage()}
          <PDFView
            fadeInDuration={250.0}
            style={styles.pdfContainer}
            fileFrom={fileFrom}
            resource={pdfLink}
            resourceType={resourceType}
            onLoad={() => {
              this.hideSpinner();
              console.log(`PDF rendered from ${resourceType}`);
            }}
            onError={error => {
              this.hideSpinner();
              console.log('Cannot render PDF', error);
            }}
          />
          {loading && this.renderSpinner()}
        </View>

// styling: 

pdfContainer: {
    flex: 1,
    marginTop: ScalePerctFullHeight(2.5),
    marginLeft: ScalePerctFullWidth(2.5),
    marginRight: ScalePerctFullWidth(2.5),
    marginBottom: ScalePerctFullHeight(2.5),
    fontSize: 20,
  },

**Comment by MartinGryner** [comment]
Can confirm. Does not happen on emulator, but does appear on iPhone X and 11.

**Comment by sanderfrenken** [comment]
Also using demo project you can reproduce this?

**Comment by SrikaraBhat** [comment]
> Can confirm. Does not happen on emulator, but does appear on iPhone X and 11.
Yes, I observed in external device, Iphone X

**Comment by sanderfrenken** [comment]
We can reproduce the issue as well, but not in the demo project. We will investigate it in coming week, if you have any leads why this happens in the mean time please let us know

**Comment by haakandev** [comment]
@rumax @sanderfrenken Seeing this issue as well (on iPhone 11/iOS 14.2). Any chance of getting a fix to it?

**Comment by Jackyang-SS** [comment]
I got the same problem, the scrollbar shows in the middle of the screen on simulator and devices.  any solutions ?
