### ISSUE TITLE
Android hits error when trying to load PDF that is secured with a password

### ISSUE THREAD

**Issue by hannzern** [rumax/react-native-PDFView#153]
**Describe the bug**
Android is getting an error of 
"Cannot render PDF 
Object {
  "message": "error: Password required or incorrect password.",
}"

**To Reproduce**
- [X ] I checked the demo project and cannot reproduce the issue
- [X ] I checked the demo project and the issue exists

1. Render PDF that is secured with a password

**Expected behavior**
To be like iOS like the screenshot below

**Screenshots**
![Screenshot 2020-01-16 at 1 52 50 PM](https://user-images.githubusercontent.com/49383330/72497464-8c9b5b00-3867-11ea-9c00-dfe0f5c2f1bc.png)
Android should show pdf just like iOS but its hitting the error straight without rendering

**Smartphone (please complete the following information):**
 - Device: Pixel 3a XL
 - OS: Android 10.0
 - Version 29

**Comment by rumax** [comment]
Hi @hannzern, Android and iOS have different implementation. iOS uses WKWebView and that's it is ok, but on android the password need to be set before the component is rendered. Will you be able to create a PR with proposed feature?

**Comment by eramudeep** [comment]
how did you gave the password to pdf file, in props ??
