### ISSUE TITLE
Not showing annotations

### ISSUE THREAD

**Issue by JeremyBradshaw7** [rumax/react-native-PDFView#154]
We're getting a customer complaint that annotations made to a pdf are not showing in this pdf viewer. We haven't yet found out how these annotations are made.

**To Reproduce**
Try viewing the attached through the library, should have some annotations which do show up on mac/windows.
[pdf_with_annotations.pdf](https://github.com/rumax/react-native-PDFView/files/4294882/pdf_with_annotations.pdf)

**Expected behavior**
Annotations to show as on windows/mac:
![image](https://user-images.githubusercontent.com/36155348/76019922-6b2b2700-5f1a-11ea-8e09-0717fdd70443.png)

**Actual behavior**
No annotations:
![image](https://user-images.githubusercontent.com/36155348/76020019-9746a800-5f1a-11ea-8064-114260d2e4a6.png)

**Smartphone (please complete the following information):**
 - Device: ios and android

**Comment by rumax** [comment]
It see the same issue exists in AndroidPdfViewer, and AndroidPdfViewer project requires a new maintainer, which means that it will not be implemented unfortunately, sorry. But because these are opensource projects you are welcome to create a pull request with the fix.
