### ISSUE TITLE
HIPAA compliance question

### ISSUE THREAD

**Issue by mladibejn** [rumax/react-native-PDFView#155]
Hi, 

I'd just like to confirm whether the usage of the resource type as base64 or url doesnt save any PDFs to device and is only performed in memory? I'm using rn-fetch-blob to download from a url and then content sa base64 is sent to react-native-view-pdf. 

Great work and thanks! Branko.

**Comment by rumax** [comment]
Hi @mladibejn, the [viewer](https://github.com/rumax/react-native-PDFView) uses [Android PdfViewer](https://github.com/barteksc/AndroidPdfViewer) and [WKWebView](https://developer.apple.com/documentation/webkit/wkwebview), so it's good to check these project. In the viewer itself, there is, for example, a [tasks](https://github.com/rumax/react-native-PDFView/blob/master/android/src/main/java/com/rumax/reactnative/pdfviewer/PDFView.java#L161) that downloads the file to render PDF from url. But it's always a scope of your app. Anyway you can always check the source to verify it and report the issue if you find it.

**Comment by mladibejn** [comment]
Thanks @rumax for your answer. Seems like when base64 is used, in Android's part it says the data is not saved to disk and is loaded as byte array. I assume similar behaviour is ithin WKWebView as well.
