### ISSUE TITLE
No callback in iOS

### ISSUE THREAD

**Issue by JKshared92** [rumax/react-native-PDFView#156]
sometimes No callback in ios
onLoad and onError No callback
How do i know if it works

code：
<PDFView
              fadeInDuration={250.0}
              style={{ flex: 1}}
              resource={fileName}
              fileFrom={'documentsDirectory'}
              resourceType={'file'}
              onLoad={(res) => {
                console.log('===加载完成==:', res);
                ActivityIndicator.close();
              }}
              onError={(error) => {
                console.log('===加载失败==:', error);
                ActivityIndicator.close();
              }}
            />

**Comment by rumax** [comment]
@JKshared92 Hi, the best what you can do is try to reproduce it with the [demo project](https://github.com/rumax/react-native-PDFView/tree/master/demo) and desscribe the steps. Or in your project you can also debug the app and check why there is no callbacks. You can also create a [pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) with a fix.
