### ISSUE TITLE
Authorization header

### ISSUE THREAD

**Issue by sarry173** [rumax/react-native-PDFView#158]
How to set my authorization token in header for PDF view. Please exaplain.

**Comment by sarry173** [comment]
JSON value '{
  resource = "http://www.africau.edu/images/default/sample.pdf";
}' of type NSMutableDictionary cannot be converted to NSString

receiving this error

**Comment by sanderfrenken** [comment]
Can you reproduce the same issue in the demo project?

> JSON value '{
> resource = "http://www.africau.edu/images/default/sample.pdf";
> }' of type NSMutableDictionary cannot be converted to NSString
> 
> receiving this error

**Comment by sanderfrenken** [comment]
> How to set my authorization token in header for PDF view. Please exaplain.

You can add headers via `urlProps`
