### ISSUE TITLE
IOS long URLs hang indefinitely

### ISSUE THREAD

**Issue by normads** [rumax/react-native-PDFView#159]
**Describe the bug**
Long URLs are not loaded in ios

**To Reproduce**
Passing, 
https://s3-ap-southeast-2.amazonaws.com/malith.coral-attachments/03dc8/shmat_urls.pdf
as the url works as expected while passing, 
https://s3-ap-southeast-2.amazonaws.com/malith.coral-attachments/03dc8f982898ab289bca1a7967286a3055af2553fc26cb36ab7248ffb1234567/shmat_urls.pdf
as the url makes the viewer hang indefinitely without a callback. 
Both url's point to the exact same file.

**Expected behavior**
URLs should be loaded despite length.

**Comment by sanderfrenken** [comment]
Can you reproduce this in the demo project?

**Comment by rumax** [comment]
```bash
$ git diff src/resources.js
diff --git a/demo/src/resources.js b/demo/src/resources.js
index 70928f3..3d09400 100644
--- a/demo/src/resources.js
+++ b/demo/src/resources.js
@@ -20,7 +20,7 @@ const resources: {[key: string]: Resource } = {
     resourceType: 'file',
   },
   url: {
-    resource: 'http://www.africau.edu/images/default/sample.pdf',
+    resource: 'https://s3-ap-southeast-2.amazonaws.com/malith.coral-attachments/03dc8f982898ab289bca1a7967286a3055af2553fc26cb36ab7248ffb1234567/shmat_urls.pdf',
     resourceType: 'url',
   },
```

Leads to 

<img width="900" alt="Screenshot 2020-04-03 at 17 36 17" src="https://user-images.githubusercontent.com/2707180/78378852-d88dae80-75d1-11ea-92b5-95e57ef26a87.png">

@normads Please, try to debug you app to find the issue and let us know it it is in the viewer, by providing more details or a pull request with the fix.

**Comment by normads** [comment]
That's strange, I'm getting similar behavior even with the latest version 0.10.1, was on 0.4.1 earlier. Any idea what could be the cause if both `onError()` and `onLoad()` are not returning?

**Comment by normads** [comment]
Nevermind, i think i found the issue :) the error occurs when the Content-Type header of the get request doesn't contain 'application/pdf'
It is a problem with my file upload mechanism, but it would be nice if this could be captured in an error. 
Thanks!
