### ISSUE TITLE
[iOS]: onError is not called

### ISSUE THREAD

**Issue by artyorsh** [rumax/react-native-PDFView#162]
**Describe the bug**

👋 First of all, thanks for creating this library. It is really light-weight and gives an ability to display pdf's quickly without a need to parse blobs and stuff like that (comparing to the alternative solutions 😄). Pretty handy.

Anyways, I stuck into the problem when there is a 404 server response, and instead of calling `onError`, `onLoad` is called. I'm not sure if onError should be called for 4xx codes, but there is no way to know if the response was successful, because onLoad is called with no arguments.

This is however is valid for iOS, since on Android `onError` is called.

See [screenshot for iOS](https://imgur.com/a/byNYAV0).
See [screenshot for Android](https://imgur.com/a/zaMMisq).

**To Reproduce**

Our implementation is quite tricky. We use an api request which normally returns a pdf stream:

![image](https://user-images.githubusercontent.com/10753921/80111201-42bdc180-8588-11ea-888f-3bae2e1698fc.png)

Which works as expected and pdf is displayed. But in case of 404 server response, onLoad is called and the stack trace is displayed. 

- [ ] I checked the demo project and cannot reproduce the issue
- [ ] I checked the demo project and the issue exists

```
<PDFView
  resource={'https://server.com/api/path-to/pdf?token=someauth'}
  onLoad={() => { ... } }
  onError={() => { ... }}
/>
```

**Expected behavior**

I would expect `onError` to have been called. Also, having `onLoad` called with an information about the response is also a good option.

**Additional context**
```
➜ npx envinfo --preset react-native

  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 13.2.0 - ~/.nvm/versions/node/v13.2.0/bin/node
    Yarn: 1.19.2 - ~/.nvm/versions/node/v13.2.0/bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v13.2.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-23 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
  IDEs:
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
```

**Comment by sarry173** [comment]
hi did you find any solution for this issue, I m also facing it.
