### ISSUE TITLE
"PDF file not found"

### ISSUE THREAD

**Issue by JeremyBradshaw7** [rumax/react-native-PDFView#167]
**Is your feature request related to a problem? Please describe.**
Trying to render a pdf that I've cached locally, it shows the error in the title.

**Describe the solution you'd like**
Allow a locally cached file to be rendered via the file:// protocol, or a full path.

**Comment by JeremyBradshaw7** [comment]
closed, trying the 'file' type, though still getting issues...

**Comment by rumax** [comment]
Hi @JeremyBradshaw7 did you check https://github.com/rumax/react-native-PDFView/blob/master/demo/src/resources.js#L18
? Try to check you file in the demo project too.

**Comment by JeremyBradshaw7** [comment]
With the 'file' resourceType, I can't pass a full path for the file, eg. /Users/jeremybradshaw/Library/Developer/CoreSimulator/Devices/9F38150D-DDE1-4040-BF14-023A7729E84C/data/Containers/Data/Application/05BB31EF-9C3B-4BC7-8C82-180BCB16DB69/Library/Caches/13/9b6ef061-e07c-4113-a69f-39bc0fcf668a.pdf

It throws error "PDF file not found"

Are we restricted to only the folders supported by the `fileFrom` parameter? As you can see my store is in the Caches folder, and this isn't an option in `filesFrom` as far as I can see.

**Comment by rumax** [comment]
Hi @JeremyBradshaw7, for more information about supportred file locations you can check [getFileURL method](https://github.com/rumax/react-native-PDFView/blob/master/ReactNativeViewPDF/RNPDFView.m#L111) and [fileFrom](https://github.com/rumax/react-native-PDFView/blob/master/src/RNPDFView.js#L52) definition. That is implemented according to the [file system](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html).

So in your case it looks like you need [Library](https://github.com/rumax/react-native-PDFView/blob/master/ReactNativeViewPDF/RNPDFView.m#L117)

**Comment by vrazn** [comment]
@JeremyBradshaw7 @rumax Bumped into that today. From the Demo project resources [here](https://github.com/rumax/react-native-PDFView/blob/master/demo/src/resources.js) you can see that it passes just the name of the file (not URL) on iOS. I checked, copying the file with smth like react-native-fs to the Documents folder and then just the file name and setting resourseType to `file` works.
However, on android, you will have to pass the whole path to the file. 

I also noticed that using the `url` type and passing the `file://*your-url*` also works on iOS.

**Comment by songsterq** [comment]
Check whether https://github.com/rumax/react-native-PDFView/pull/168 fixed it? It's included in `0.11.0`. I used `url` resourceType with `file://` url after the fix and it worked fine for me in simulator and on device.
