### ISSUE TITLE
Attempted import error: 'requireNativeComponent' is not exported from 'react-native-web/dist/index'

### ISSUE THREAD

**Issue by vipulswarup** [rumax/react-native-PDFView#173]
Hi - I am getting the below error when trying to use this with Expo 3.25.0

```
Attempted import error: 'requireNativeComponent' is not exported from 'react-native-web/dist/index'
```

I installed using Yarn:
```
yarn add react-native-view-pdf
```

**Comment by rumax** [comment]
Hi @vipulswarup, `react-native-PDFView` does not work with `Expo`. I do not think that it will be a solution for you, but you can take a look to https://docs.expo.io/expokit/eject/?redirected#you-might-want-to-eject-if. Also `react-native-web` seems to be another dependency?

**Comment by vipulswarup** [comment]
Thanks @rumax ... I have already switched to react native cli ... it is working there.
