### ISSUE TITLE
Space is not showing between pages in android

### ISSUE THREAD

**Issue by shalinivathra** [rumax/react-native-PDFView#174]
Hi,
I used this library it's working good both iOS and Android. In iOS space is showing between pages, but in android the space is not showing between pages.
Could you please suggest me how to show the space between pages in android.
Thanks

**Comment by rumax** [comment]
By default spacing `10` is used, you can check it here https://github.com/rumax/react-native-PDFView/blob/master/android/src/main/java/com/rumax/reactnative/pdfviewer/PDFView.java#L120. In demo project that leads to the result:

<img width="379" alt="Screenshot 2020-10-03 at 12 24 45" src="https://user-images.githubusercontent.com/2707180/94989278-bae6d500-0573-11eb-93cc-bd83cdf6ab24.png">

That you can change by changing the style 

```
$ git diff src/styles.js
diff --git a/demo/src/styles.js b/demo/src/styles.js
index 0017c85..bb9dd08 100644
--- a/demo/src/styles.js
+++ b/demo/src/styles.js
@@ -24,7 +24,7 @@ export default StyleSheet.create({
     paddingVertical: 8,
   },
   tabButtonActive: { backgroundColor: cBlue },
-  pdfView: { flex: 1, backgroundColor: cGrey },
+  pdfView: { flex: 1, backgroundColor: 'red' },
   noContent: { flex: 1, alignItems: 'center', backgroundColor: cGreen },
   noContentText: {
     fontSize: 22,
```

in https://github.com/rumax/react-native-PDFView/blob/master/demo/src/styles.js#L27 and get result as:

<img width="386" alt="Screenshot 2020-10-03 at 12 26 31" src="https://user-images.githubusercontent.com/2707180/94989299-e7025600-0573-11eb-963a-d6bfb410d25a.png">

So I think you need to check styles in your project.
