### ISSUE TITLE
When selecting file from mobile device it does not show selected file

### ISSUE THREAD

**Issue by NKGS** [rumax/react-native-PDFView#175]
**Describe the bug**
I have file picker in my app so have used DocumentPicker to select file from device.
Once I get uri which looks something like 'content://com.android.providers.downloads.documents/document/10749' I try to load it on PDFView but it does not render, neither does it gives any error.
Also I tried option of converting file in base64 and then view it but that too does not work.

**To Reproduce**

#Approach 1 - using url
    const res = await DocumentPicker.pick({
            type: [DocumentPicker.types.allFiles],
        });
this.setState({
docPath: res.uri
})

render() {
<View>
 <PDFView
                                                fadeInDuration={100.0}
                                                style={{borderWidth:1, flex:1}}
                                                resource={docPath}
                                                resourceType='url'
                                                onLoad={() => console.log('loaded')}
                                                onError={() => console.log('Cannot render PDF')}
                                            />
</View>
}

#Approach 2: using base64
    const res = await DocumentPicker.pick({
            type: [DocumentPicker.types.allFiles],
        });

  RNFetchBlob.fs.readFile(cleanUri,'base64')
                // files will an array contains filenames
                .then((files) => {
this.setState({
docPath: files
})
})

render() {
<View>
 <PDFView
         fadeInDuration={100.0}
                                                style={{borderWidth:1, flex:1}}
                                                resource={docPath}
                                                resourceType='base64'
                                                onLoad={() => console.log('loaded')}
                                                onError={() => console.log('Cannot render PDF')}
                                            />
</View>
}

1. Render PDF with 'url/base64'

**Expected behavior**
It is expected to show PDF

**Smartphone (please complete the following information):**
 - Device: Mi A1
 - OS: android

**Additional context**
"react-native-view-pdf": "^0.10.1",
"react": "16.11.0",
"react-native": "0.62.0",

**Comment by rumax** [comment]
Hi @NKGS, I do not know `DocumentPicker` and do not use it, but didn't have any issues with reading from the file systems, as long as the app has permission to read. 

What I also see is that you get:

> content://com.android.providers.downloads.documents/document/10749

but looking at https://www.npmjs.com/package/react-native-document-picker and example there I see:

```
let url = 'file://whatever/com.bla.bla/file.ext'; //The url you received from the DocumentPicker
```

which starts with the `file`, not `content`.

Can you try to debug and check what you get in `render` method of the `PDFView.java`. You should get to the https://github.com/rumax/react-native-PDFView/blob/master/android/src/main/java/com/rumax/reactnative/pdfviewer/PDFView.java#L201 and as a result to 

```
private void renderFromFile(String filePath) {
        InputStream input;

        try {
            if (filePath.startsWith("/")) { // absolute path, using FS
                input = new FileInputStream(new File(filePath));
            } else { // from assets
                AssetManager assetManager = context.getAssets();
                input = assetManager.open(filePath, AssetManager.ACCESS_BUFFER);
            }

            configurator = this.fromStream(input);
            setupAndLoad();
        } catch (IOException e) {
            onError(e);
        }
    }
```

**Comment by NKGS** [comment]
Hi rumax,

I realized that DocumentPicker approach uri is content uri which is not working in the library. 

So I figured fetching file path using below function
```
RNFetchBlob.fs.stat(res.uri)
         .then((stats) => {
                           console.log(stats)
                        })
                        .catch((err) => {
                            console.log(err)
                        })
```

Also I used type as file and it worked fine.

Appreciate your inputs.
