### ISSUE TITLE
NSURLErrorDomain error -999

### ISSUE THREAD

**Issue by JeremyBradshaw7** [rumax/react-native-PDFView#177]
Having upgraded to React Native 0.63.3 I'm getting the above error repeatedly on loading PDFs on iOS (though they do eventually load anyway).

**Expected behavior**
onError not to fire unless there's a good reason

**Screenshots**
![image](https://user-images.githubusercontent.com/36155348/94933753-bc0bf980-04c2-11eb-90b5-d11995478605.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS11.4]

**Comment by rumax** [comment]
Hi @JeremyBradshaw7, thanks for reporting. I do not use RN `0.63.*` at this moment, but going to look into it and also update RN un demo project, because will need RN 0.63 soon. Meantime maybe you can also try to debug to check the issue?

**Comment by rumax** [comment]
I've upgrader RN in demo project https://github.com/rumax/react-native-PDFView/pull/178 and do not see any issues

<img width="697" alt="Screenshot 2020-10-03 at 18 03 02" src="https://user-images.githubusercontent.com/2707180/94996316-3b252e80-05a4-11eb-83e4-830ae46ab4b7.png">

Can you try different URL and see what happens?
