### ISSUE TITLE
Web link handling & navigation

### ISSUE THREAD

**Issue by JeremyBradshaw7** [rumax/react-native-PDFView#181]
ios handles web links in pdfs (being based on wkwebview) and I understand android can be made to as per the README (though I haven't verified this yet, the documentation suggests it works for hyperlinks within the PDF rather than web links?). However, I cannot see any way to allow the user to navigate from the linked web page back to the PDF. Where a PDF contains multiple links this is critical. Also the user may navigate elsewhere and want to step pack/forward.

Ideally the component should have goBack/goForward methods to navigate back and forward within the web session history, like react-native-webview, plus a onNavigationStateChange callback to allow the caller to determine whether back/forward is possible.

Maybe the reload method is a way to navigate back to the PDF (I intend to try this).

**Comment by rumax** [comment]
Hi @JeremyBradshaw7, for iOS it is possible to use `[webview goBack];`, but that will require new method in the bridge. And the app can render buttons for that. 
Another option I see is try to disable links.
Would you like to create a PR for that?

**Comment by mir4a** [comment]
I faced similar issue. Ideally would be nice to have `onNavigationStateChange` callback to be able to stop loading and open the link in system browser. Disabling links is not an option, since my main motivation to use this package was working links.

**Comment by mir4a** [comment]
What do you think, @rumax? Any chance that you'd be available to introduce this feature anytime soon?
