### ISSUE TITLE
App Crashes on build.

### ISSUE THREAD

**Issue by Neel97** [rumax/react-native-PDFView#182]
Hi,
Post installing the react-native-view-pdf & successful app build (android), The app crashes.
I performed adb logcat to check whats wrong and got AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application com.pdfAPP.MainApplication: java.lang.ClassNotFoundException: Didn't find class "com.pdfAPP.MainApplication".

Kindly look into it as soon as possible.
Thanks!

**Comment by rumax** [comment]
Hi, @Neel97 looking at the message

> java.lang.RuntimeException: Unable to instantiate application com.pdfAPP.MainApplication: java.lang.ClassNotFoundException: Didn't find class "com.pdfAPP.MainApplication

I do not see anything related to the PDF viewer. That looks like something is wrong with the project, since it complains to the `MainApplication`
