### ISSUE TITLE
Set backgroundColor for PDF-View

### ISSUE THREAD

**Issue by LoganBwDE** [rumax/react-native-PDFView#183]
Hi :) 

I tried to manage it on my own, but it seems kinda buggy ^^
The problem is: u can't set the backgroundColor for the View

I used your demo and changed: 
`pdfView: { flex: 1, backgroundColor: cGrey }`
to
`pdfView: { flex: 1, backgroundColor: 'red' }`

You can see the color for half a second while the pdf is loading, after that the color is for ever gone :(
Is there any fix for this? :)

Greets

**Comment by rumax** [comment]
Hi @LoganBwDE, `backgroundColor: 'red' ` is a color for the View, but after it is rendered, you get a color of the PDF document page. So the only thing you can change is a spacing color with that property.
