### ISSUE TITLE
PDF is not opening for sidned APK. Loader always.

### ISSUE THREAD

**Issue by ArkanRomanWork** [rumax/react-native-PDFView#185]
**Is your feature request related to a problem? Please describe.**
PDF file not loading in android **signed APK** for http. Need only https
PDF files I receive from API which located on Amazon s3 without any restriction. Example: `http://s3.amazonaws.com/solasalonstudios/deals/files/000/000/236/original/Barbicide_Linked_Sheet.pdf?1608758993`

When I build apk - works fine.
When I build signed apk - I see loader always.

**Describe the solution you'd like**
Please add this info to readme. For ios - all ok. For android - all ok for build apk, but for **signed APK** - not working.

**Comment by rumax** [comment]
Hi @ArkanRomanWork is it your issue? https://stackoverflow.com/questions/51902629/how-to-allow-all-network-connection-types-http-and-https-in-android-9-pie
