### ISSUE TITLE
Links in the pdf document is not clickable on android

### ISSUE THREAD

**Issue by kamalapbt** [rumax/react-native-PDFView#187]
**Describe the bug**
If pdf document has any hyper links, they are not clickable on android

react-native-view-pdf: 0.11.0
react-native: 0.62.2

**Comment by rmathias86** [comment]
Any update on this? I'm facing the same issue here

**Comment by rumax** [comment]
Hi @kamalapbt @rmathias86 according to https://github.com/barteksc/AndroidPdfViewer#links 

> By default, DefaultLinkHandler is used and clicking on link that references page in same document causes jump to destination page and clicking on link that targets some URI causes opening it in default application

but you need version 3.0.0 of the viewer

**Comment by kamalapbt** [comment]
@rumax I tried with latest version of AndroidPdfViewer by setting project build.gradel 
  ext {
    ...
    pdfViewer = "3.1.0-beta.1"
  }
but it didn't fix the issue. Is there any plan to fix it soon?

**Comment by rumax** [comment]
Hi @kamalapbt you need to check you project and settings. I just checked [demo project](https://github.com/rumax/react-native-PDFView/tree/master/demo), which uses `pdfViewer = "3.1.0-beta.1"` and no issues, links work fine


https://user-images.githubusercontent.com/2707180/115297204-3a2ca680-a15c-11eb-8009-0558fd9b45ca.mov

**Comment by kamalapbt** [comment]
@rumax yes it works mostly. but there are some files which are not able to launch links on android. Find attached file here with broken link.
[Test PDF with link.pdf](https://github.com/rumax/react-native-PDFView/files/6388002/Test.PDF.with.link.pdf)

**Comment by dmeij** [comment]
Add this in AndroidManifest for permission in Android 11 and above:

`<queries>
    <intent>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="http" />
    </intent>
</queries>`

In combination with pdfViewerVersion = "3.2.0-beta.1" in build.gradle.
