### ISSUE TITLE
Can i set page like scroll to first page and last page of the PDF ?

### ISSUE THREAD

**Issue by raginieulogik** [rumax/react-native-PDFView#188]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rumax** [comment]
To have that functionality, both AndroidPdfViewer and WKWebView should allow to do that. And in AndroidPdfViewer I do not see that functionality. If you find it or know how to do, you can create a PR with the functionality, or let me know more details.
