### ISSUE TITLE
PDF view disappears from flatlist items on scrolling the list 

### ISSUE THREAD

**Issue by Binary-Ketan** [rumax/react-native-PDFView#190]
I have flatlist which renders multiple cards on which the PDF view is set. When I scroll below first row of cards and scroll up again. The pdf view on card disappears and shows empty.

**Comment by rumax** [comment]
Hi @Binary-Ketan , thank you for reporting the issue. I'm not sure why it happens and cannot find anything wrong in the component (meantime if you know, please, let me know). But as a quick fix you can disable [removeclippedsubviews](https://reactnative.dev/docs/flatlist#removeclippedsubviews)

**Comment by Binary-Ketan** [comment]
Hi @rumax , thank you for the quick fix. Its working as expected now after using removeClippedsubviews .

**Comment by minhna** [comment]
I'm having the same problem. When navigating to other screen and returning back to the Flatlist screen, the blank page appears.

**Comment by minhna** [comment]
I added a button to reload the PDF and it appears again.

**Comment by chandni-solanki** [comment]
Having same issue on navigation. moreover reload function is not working.
