### ISSUE TITLE
PDF file not rendering

### ISSUE THREAD

**Issue by coderkot** [rumax/react-native-PDFView#194]
**Describe the bug**
Hi! I'm trying to render pdf file by url. onLoad method works and show in console success message, no errors, but on View never happend and shows it empty.

**To Reproduce**
<View>
          <PDFView
            style={{ flex: 1 }}
            resource={'https://riptutorial.com/Download/react.pdf'}
            resourceType={'url'}
            onLoad={() => console.log('PDF rendered from url')}
            onError={(error) => console.log('Cannot render PDF', error)}
          />
</View>

**Screenshots**
![image](https://user-images.githubusercontent.com/48554890/126975588-4b6d3ce3-f66b-43d5-bc22-723f1bd59d4d.png)
![image](https://user-images.githubusercontent.com/48554890/126975655-166ea7db-eb63-4082-9435-923c5575f387.png)

**Smartphone (please complete the following information):**
 - Android SDK built for x86
 - Android 10

"react-native": "0.64.0"

**Comment by coderkot** [comment]
As solution: if you are using PDF Viewer inside another View container this View container must have the style props with Width & Height.

**Comment by ayozebarrera** [comment]
I'm having this problem after update the package. It was working before. 

The width & height solution didn't work. Any help? 

I'm using the dummy pdf to discard any external problems but no pdf appearing. On the other hand, I loaded a pdf with multiple pages and I can scroll between pages (the current page and max page is appearing, but the pdf not)
