### ISSUE TITLE
Zoom in and Zoom out not working

### ISSUE THREAD

**Issue by sarry173** [rumax/react-native-PDFView#195]
How to enable Zoom in and Zoom out not working

**Comment by rumax** [comment]
What do you mean exactly? It does work.

**Comment by sarry173** [comment]
there is no zoom functionality available

**Comment by rumax** [comment]
Both, zoom in and out are fine: 

https://user-images.githubusercontent.com/2707180/128866012-beb1a7ac-c688-4306-b7ce-a47234371fbb.mov

**Comment by sarry173** [comment]
Trying on ios but still not working , is there any code for enabling zoom function

**Comment by sarry173** [comment]
thanks its Working
