### ISSUE TITLE
Url with query Param not working in iOS

### ISSUE THREAD

**Issue by sarry173** [rumax/react-native-PDFView#197]
In ios if URL has Query params like 
api/v2/view?filter={"caseRef.uuid":"1000859035,"pRef.mrn":"10244957"}

PDF not working and showing error
Cannot render PDF {"message": "Protocol (null) is not supported", "target": 1203, "title": "Error occured while loading content in webview"}

it is woking in android 

Please help to fix this issue .

**Comment by yu-carter** [comment]
Perhaps the 'Contents-Type' of your response header is not 'application/pdf'.

**Comment by rumax** [comment]
Fix should be available in v0.12.0

**Comment by emeraldsanto** [comment]
> Hi @rumax, fix for this in v0.12.0 caused issue with properly encoded urls on iOS. Probably because it started encoding it twice after update. The error I was getting was: `resource https://pf2-patient-files-staging.s3.us-e…a97e71a520f8cbc6db in unreachable, statusCode 400`
> 
> This encoding shouldn't be part of the library (or it should be behind param to encode it). For someone encountering the same issue, the solution is to revert to previous version. I used `v0.11.0`. If you need help with reproducing it, let me know. I can also open a new ticket for it but I'm quite sure it is related to the above change.
> 
> Keep up the good work!

I had the same problem with an S3 URL, reverting to `0.11.1` did the trick 😬

**Comment by rumax** [comment]
Hi @abarisic86, do you encode it first time in your app?

**Comment by abarisic86** [comment]
No, but I get the url encoded from the server. So, yes, url is already
encoded.

sri, 3. stu 2021. u 22:06 Maksym Rusynyk ***@***.***> napisao
je:

**Comment by rumax** [comment]
Change with encoding is reverted and available in 0.12.2. encoding has to be done on JS/app side
