### ISSUE TITLE
jitpack.io android-pdf-viewer-2.8.2.pom 401 Unauthorized

### ISSUE THREAD

**Issue by tylerforsythe** [rumax/react-native-PDFView#204]
**Describe the bug**
401 received trying to GET 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom' during `npx react-native run-android`.

**To Reproduce**
Unable to get the demo project to even begin building via `npm install` or `yarn install`. So I was unable to get to the `run-android` step in the sample.

```
rm -rf node_modules
yarn install [or npm install]
npx react-native run-android
```

**Expected behavior**
That the build successfully pulls any needed react-native-PDFView files.

**Screenshots**
Build log output below. Note the pertinent bit is:
```
Could not GET 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'.
Received status code 401 from server: Unauthorized
```

Attempting to access 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom' directly in a browser prompts for a username and password, which explains the error. It seems like the password prompt shouldn't be happening. My understanding is that because this is an open source project, the jitpack hosting should be free and open. Perhaps something changed with the host service of this file?

![image](https://user-images.githubusercontent.com/1689004/137396730-5c37d628-2830-4ba5-beca-394e7865cb5e.png)

```
PS C:\home\projects\custom-mobile-app> npx react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1198 file(s) to forward-jetify. Using 16 workers...
info JS server already running.
info Installing the app...

> Configure project :app
WARNING:: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed in version 7.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
WARNING:: Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.
This repository is deprecated and it will be shut down in the future.
See http://developer.android.com/r/tools/jcenter-end-of-service for more information.
Currently detected usages in: project ':react-native-async-storage_async-storage', project ':react-native-screens', project ':react-native-svg', ...

> Task :app:checkDebugAarMetadata FAILED
16 actionable tasks: 2 executed, 14 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.barteksc:android-pdf-viewer:2.8.2.
     Required by:
      > Could not resolve com.github.barteksc:android-pdf-viewer:2.8.2.
         > Could not get resource 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'.
            > Could not GET 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'. Received status 
code 401 from server: Unauthorized

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. 
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.barteksc:android-pdf-viewer:2.8.2.
     Required by:
         project :app > project :react-native-view-pdf
      > Could not resolve com.github.barteksc:android-pdf-viewer:2.8.2.
         > Could not get resource 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'.
            > Could not GET 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'. Received status 
code 401 from server: Unauthorized

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s

    at makeError (C:\home\projects\custom-mobile-app\node_modules\execa\index.js:174:9)
    at C:\home\projects\custom-mobile-app\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runOnAllDevices (C:\home\projects\custom-mobile-app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:106:5)
    at Command.handleAction (C:\home\projects\custom-mobile-app\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:186:9)
info Run CLI with --verbose flag for more details.
```

**Smartphone (please complete the following information):**
Samsung SM-G920V (Verizon Galaxy S6)

**Additional context**
Android Studio Arctic Fox 2020.3.1 patch 2 built August 26, 2021 running on Windows 10.
Problem seems to be Android-build only. Works fine on my Mac Mini M1 and iOS iPhone 12 Pro. In fact, it runs great on my iOS device -- thanks for this awesome package.

**Comment by rumax** [comment]
Hi @tylerforsythe ,

Do you have jcenter repository? Because you need to use it, com.github.barteksc:android-pdf-viewer comes from there. https://github.com/barteksc/AndroidPdfViewer#installation:

> Library is available in jcenter repository, probably it'll be in Maven Central soon.

**Comment by tylerforsythe** [comment]
Hi @rumax and @teaganharatua , thanks for your responses. I tried installing version 0.11.1 specifically but did not have success building whether for my real device or emulator. I receive the same 401 error.

@rumax I'm not sure what you mean by "do you have jcenter repository". Do I need to install something? Whenever I search "JCenter Repository" or go to the jfrog website, I don't see anything about downloading a JCenter Repository tool of any kind, only lots of news articles that JCenter is now end-of-life. The top result points me to https://jcenter.bintray.com/ which just displays a generic nginx 403 Forbidden message.

I see from your installation instructions link that I need to put `implementation 'com.github.barteksc:android-pdf-viewer:2.8.2'` into my build.gradle file. Will you please assist me with where to put it exactly? I'm extremely unfamiliar with typical Android build setup. It looks like I have two of these files: 

1) myapp\android\app\build.gradle
2) myapp\android\build.gradle

It appears that it should go into file 1, but I tried putting it in a couple different spots without success. I currently have it in file 1, under `dependencies {`, under the `implementation "com.facebook.react:react-native:+"` line.

```
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation 'com.github.barteksc:android-pdf-viewer:2.8.2'
...
```

I still receive a 401 during build for the jitpack.io URL.

Thanks!
