### ISSUE TITLE
Enable or Disable selection and copy text

### ISSUE THREAD

**Issue by coderkot** [rumax/react-native-PDFView#210]
It would be great feature to enable\disable selection and copy text in pdf.
On Android device I can't to select and copy text
And on iOS device I can to select and copy text.

**Comment by rumax** [comment]
Hi @coderkot , PDFViewer uses https://github.com/barteksc/AndroidPdfViewer on Android. Unfortunately I cannot find such a possibility there and therefore I will not be able to add such functionality. In case you know a solution how to do it, please, let me know.

**Comment by Winxpina** [comment]
@rumax I have the same problem
