### ISSUE TITLE
Suggestion to change Android Native Repo not depend on jcenter()

### ISSUE THREAD

**Issue by gwijaya94** [rumax/react-native-PDFView#212]
**Description**
Currently I'm using RN 0.66.x with gradle 4.2.2.
I have removed jcenter() and change it to mavenCentral().
When I apply this library, it has problem getting the Android Native Pdf.

@rumax
Can it be change to support mavenCentral?
Here's some alterative Android Pdf with mavenCentral(): [mhiew/AndroidPdfViewer](https://github.com/mhiew/AndroidPdfViewer)
The library is forked from [barteksc/AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer)

Here some reference about this problem : https://github.com/barteksc/AndroidPdfViewer/issues/1005

**Screenshots**

- [build.gradle from mhiew/AndroidPdfViewer](https://github.com/mhiew/AndroidPdfViewer/blob/master/build.gradle)

> <img width="462" alt="Screen Shot 2022-01-06 at 12 52 46" src="https://user-images.githubusercontent.com/65438712/148335467-ab689e73-d9a8-49d1-afcd-19676e397a8f.png">

- [build.gradle from barteksc/AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer/blob/master/build.gradle)

> <img width="579" alt="Screen Shot 2022-01-06 at 12 52 28" src="https://user-images.githubusercontent.com/65438712/148335445-43a9bc43-dff8-4db5-9de7-e988d0e70f3e.png">

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4a 
 - OS: Android 12

**Comment by Adaverse** [comment]
Any thoughts on it?

**Comment by rumax** [comment]
Hi @gwijaya94 , thanks for the feedback. What you say is you want 

> implementation "com.github.barteksc:android-pdf-viewer:$pdfViewerVersion"

to be 

> implementation "com.github.mhiew:android-pdf-viewer:$pdfViewerVersion"

correct?

I think as an option I can check if it is possible to define in in a host app in a same way how it is done for the version.

**Comment by rumax** [comment]
Please check version 0.13.0

**Comment by Critically** [comment]
Update to 0.13.0, add   
`pdfViewerVersion = "3.2.0-beta.1"
pdfViewerViewerRepo = "com.github.mhiew" `
to my build.gradle

![Скриншот 16-01-2022 140924](https://user-images.githubusercontent.com/4048161/149657449-a1aeb653-3fd2-4ffe-819e-af86bb748e2a.jpg)


But still not work, when  i try to use npx react-native run-android i got `Could not get resource 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/3.2.0-beta.1/android-pdf-viewer-3.2.0-beta.1.pom'`

Can u please say, what i'm doing wrong ?

**Comment by rumax** [comment]
Hi @Critically, I did typo in docs, it has to be `pdfViewerRepo`. Please, change it in your gradle script.
