### ISSUE TITLE
Import from 'react-native-view-pdf' not work

### ISSUE THREAD

**Issue by Critically** [rumax/react-native-PDFView#214]
**Describe the bug**
After 0.13.0 import PDFView from 'react-native-view-pdf' stop working for me, may be it's my fault
In metro.config.js i have   
resolver : {
    sourceExts: ['jsx', 'js', 'ts', 'tsx', 'json']
  },

**Screenshots**
![Скриншот 17-01-2022 11_10_07](https://user-images.githubusercontent.com/4048161/149731676-0c0c8692-a11f-4d2c-8e1d-738a8de155b3.jpg)

**Additional context**
Solution for me is to use: 'react-native-view-pdf/src/index'

**Comment by rumax** [comment]
Package republished. Please check version 0.13.2.
