### ISSUE TITLE
Could not get resource 

### ISSUE THREAD

**Issue by WilongChen** [rumax/react-native-PDFView#216]
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.barteksc:android-pdf-viewer:2.8.2.
     Required by:
         project :app > project :react-native-view-pdf
      > Could not resolve com.github.barteksc:android-pdf-viewer:2.8.2.
         > Could not get resource 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'.
            > Could not GET 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'. Received status code 401 f
rom server: Unauthorized

**Comment by saransh-malik** [comment]
You are probably not using jcenter in your repositories, see the readme on how you can use this package without using jcenter.

**Comment by rumax** [comment]
@saransh-malik thanks for the comment
@WilongChen yes, JCenter or mavenCentral is needed for Barteksc PdfViewer or mhiew/AndroidPdfViewer. Please, check that you have it defined in your gradle script.
