### ISSUE TITLE
With React Navigation, The PDF View Get Dissapers

### ISSUE THREAD

**Issue by chandni-solanki** [rumax/react-native-PDFView#217]
**Describe the bug**
For PDF view, while working with react navigation, it gets disappear.

**To Reproduce**
- integrate react native navigation
- create 2 screen component
- From PDFView screen, go to next screen, on back button click, verify the behaviour
- PDF view will get dissaper

**Note
- I checked the demo project and it is reproducible there as well

**Comment by DayvsonAlmeida** [comment]
Same issue here.

**Comment by phanvungoc96** [comment]
same Issue when I move between two tabs has PDF, my PDF disappears and my app crash later

**Comment by wthew** [comment]
it's possible to work around using `useFocusEffect` from "react navigation" and reloading the `resource` prop

**Comment by sambeetsahu** [comment]
@wthew are yo able to resolve the issue with useFocusEffect and reloading 
can you please guide on this I am facing the same issue

**Comment by MuazzezA** [comment]
I found the solution 🥳

First you should use https://reactnavigation.org/docs/use-focus-effect/ . But that's definitely not enough. As a suggestion, you can give the **key property** to the PDFView component and connect it to the loading status, like key={loading ? 1:0} 
If you don't use the key, the other one doesn't matter. 

I hope it helps.
