### ISSUE TITLE
iOS Build Error - Link RNPDF (arm64)

### ISSUE THREAD

**Issue by Himatheja** [rumax/react-native-PDFView#221]
Latest version of react-native-view-pdf is installed and I'm getting this error on Xcode 13.3 (newly installed) and this was not happening on Xcode 12.5.

<img width="742" alt="Screenshot 2022-03-29 at 5 10 24 PM" src="https://user-images.githubusercontent.com/29119638/160604117-bd477ad3-33be-4e41-80b7-fcba995773f3.png">

 "react-native": "0.63.3",
 "react-native-view-pdf": "0.12.2",

Also used tried with the latest version  "react-native-view-pdf": "0.13.2" . Still facing the above issue screenshot attached.

Can anyone help me here?

**Comment by c-basso** [comment]
Hi, i'm tried to add this code
```
pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name.eql?('RNPDF')
        def pod.build_type
          Pod::BuildType.static_library
        end
      end
    end
  end
```
to Podfile and it works

found solution here https://github.com/software-mansion/react-native-screens/issues/842#issuecomment-790498006
