### ISSUE TITLE
Received status code 401 from server: Unauthorized

### ISSUE THREAD

**Issue by rakmobility** [rumax/react-native-PDFView#226]
Building for Android and getting:
 Required by:
         project :app > project :react-native-view-pdf
      > Could not resolve com.github.barteksc:***-pdf-viewer:2.8.2.
         > Could not get resource 'https://jitpack.io/com/github/barteksc/***-pdf-viewer/2.8.2/***-pdf-viewer-2.8.2.pom'.
            > Could not GET 'https://jitpack.io/com/github/barteksc/***-pdf-viewer/2.8.2/***-pdf-viewer-2.8.2.pom'. Received status code 401 from server: Unauthorized
   > Could not resolve com.henninghall.***:NumberPickerView:1.1.1.

    "react-native-view-pdf": "0.13.2",

Using below repos:
 repositories {
        mavenLocal()
        mavenCentral()
        google()
        maven { url 'https://maven.google.com' }
        maven { url("https://jitpack.io") }
        maven { 
            url "https://maven.fabric.io/public"
        }
    }

**Comment by ConorLindsay94** [comment]
Exact same issue here - using latest version

**Comment by ConorLindsay94** [comment]
According to https://github.com/rumax/react-native-PDFView/issues/204 - This is due to not including jcenter() in the build.gradle file. Will this not be an issue with jcenter shutting down?

**Comment by calintamas** [comment]
Indeed, adding `jcenter()` to `android/build.gradle` fixes the issue. They say that jcenter is in readonly mode indefinitely, so I suppose it should be fine for now.

```gradle
// android/build.gradle

allprojects {
    repositories {
        ...
        jcenter()
    }
}
```

**Comment by rumax** [comment]
> any update on this solution?

Did you try an alternative solution mentioned in readme? 

> Barteksc PdfViewer uses JCenter, which should be [read-only indefinitely](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), but in case the host project does not use it, there is a possibility to use [mhiew/AndroidPdfViewer](https://github.com/mhiew/AndroidPdfViewer) which is a fork published on mavenCentral.

**Comment by Nayan014** [comment]
After trying numerous solutions, this one finally worked for me. [Link](https://github.com/DImuthuUpe/AndroidPdfViewer/issues/1037#issuecomment-2307015289)
