### ISSUE TITLE
React Native 0.68.2: "Warning: ViewPropTypes will be removed from React Native."

### ISSUE THREAD

**Issue by JoniVR** [rumax/react-native-PDFView#227]
**Describe the bug**
I just upgraded to React Native 0.68.2, and got the following warning:
`ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.`

The stacktrace traced back to this (awesome and much appreciated) library. If I do a search query, I can indeed find [the offending lines](https://github.com/rumax/react-native-PDFView/search?q=ViewPropTypes).

**To Reproduce**

- [ ] I checked the demo project and cannot reproduce the issue
- [ ] I checked the demo project and the issue exists

**Seems not relevant as demo project isn't up-to-date yet.**

1. Use the library in a project with React native 0.68.2 or higher (not sure which exact version started it).
2. See warning

**Expected behavior**
No warnings

**Screenshots**
![image](https://user-images.githubusercontent.com/7591717/168039400-6a1b1a57-1a68-43f9-851e-1b42f87c9aef.png)

**Smartphone (please complete the following information):**
 - Device: iPad Air 5th generation
 - OS: iOS
 - Version 15.4

Though it'll be present on all brands and devices probably.

**Additional context**
The warning itself suggests using 'deprecated-react-native-prop-types', but perhaps a better migration path is possible? (thinking Typescript for example)

**Comment by JoniVR** [comment]
Not stale.....

**Comment by rumax** [comment]
Fixed in 0.14.0
