### ISSUE TITLE
app is crashing while try to reopen different pdf in android

### ISSUE THREAD

**Issue by hareesh7777** [rumax/react-native-PDFView#248]
**Describe the bug**

**To Reproduce**

- [ ] I checked the demo project and cannot reproduce the issue
- [ ] I checked the demo project and the issue exists

1. Render PDF with '...'
2. Other actions '...'
3. See error

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

<PDFView
          resource={pdfLink}
          resourceType='url'
          style={styles.imageStyle}
          onError={(error) => {
            console.log("error is ", error);
            console.log("123456 ", pdfLink);
          }}
          onLoad={()=>console.log("hello ", pdfLink)}
   />

**Comment by rumax** [comment]
Hi @hareesh7777 What is exactly the issue and how do you know it is `react-native-PDFView ` issue? Can you provide details as it is described in template?
