### ISSUE TITLE
Reduce minSdkVersion

### ISSUE THREAD

**Issue by erikpedersen** [rumax/react-native-PDFView#34]
The build.gradle file in the Android project currently has a minSdkVersion set to 21. This seems a bit higher than necessary. I'm currently using it in a project that has a minSdkVersion of 19 and I need to override the react native project settings to allow the project to build and run with my project. Looking at the code, I'm not seeing anything that would require minSdkVersion to be 21 and I'm wondering if this could be reduced.

**Comment by rumax** [comment]
Hi @erikpedersen. The reason for the version was that the plugin was developed and tested for the project with the same configuration. I didn't test 19 (Try-with-resources requires minSdkVersion 19), but if you confirm that it works with your project, the minSdkVersion can be changed.

You can checkout branch [minSdkVersion_19](https://github.com/rumax/react-native-PDFView/tree/minSdkVersion_19) and generate npm package using `npm pack` command. The generated package can be tested in your project.

**Comment by erikpedersen** [comment]
@rumax I checked out the minSdkVersion_19 branch, ran npm pack, installed from that local package, and tested building and running in debug and release mode on an API 19 Android emulator successfully. I also was able to successfully test a release build of my project on a device running Android 19/KitKat.

**Comment by rumax** [comment]
@erikpedersen Thanks! Version 0.2.1 should contain the minSdkVersion 19
