### ISSUE TITLE
App Crashes on Page Load on IOS and Android

### ISSUE THREAD

**Issue by chakafasano88** [rumax/react-native-PDFView#40]
Getting an error ```Invariant Violation: Native component for "PDFView" dos not exist```.  I installed the package using yarn and my import is ```import PDFView from 'react-native-view-pdf```.

I've also cleaned cache and rm -rf node_modules several times.

**Comment by rumax** [comment]
Did you link the library?

**Comment by rumax** [comment]
@chakafasano88 do you still have this issue and need help? or it can be closed?

**Comment by chakafasano88** [comment]
You can close the issue, I found an alternative solution. Thank you.

**Comment by mlaco** [comment]
@chakafasano88 what was your solution? Please post!

**Comment by chakafasano88** [comment]
@mlaco 
This caused much frustration but here is a solution !

I ended up using `WebView` a PDF viewer provided by React Native. It works with ease for IOS.
However there is a small modification to make this work with Android. 

Create two variables: the first stores your url.
The second checks if the device is IOS or android:
```
    const { url } = this.props.navigation.state.params;
    const uri =
      Platform.OS === "ios"
        ? url
        : `https://drive.google.com/viewerng/viewer?embedded=true&url=${url}`;
```
If not IOS, append your url to the google URL above.

Finally, insert the uri into the `WebView`

``` 
          <WebView
            bounces={false}
            scrollEnabled={false}
            source={{ uri: uri }}
            onLoadStart={() => this._showSpinner()}
            onLoad={() => this._hideSpinner()}
          />
```

That should do the trick !!

**Comment by indapublic** [comment]
I have same behaviour for IOS. Library is installed and linked (tried by automatic and manual).

@chakafasano88 Is it possible pass headers to Google Driver Viewer?

**Comment by rumax** [comment]
@indapublic Can you, please, provide more detailed information, like can you reproduce it with demo project, what headers do you use, logs, etc.?

Without knowing the reason and assistance in finding the issue we will not be able to fix the component, if it's the issue of the component.

**Comment by indapublic** [comment]
@rumax Exception will raise in any case (file/url with/without headers).
If my code contains <PDFView>, it will fall.

![screen shot 2018-10-04 at 16 51 25](https://user-images.githubusercontent.com/856260/46457466-ca50ad80-c7f5-11e8-80fc-15fca3ec87d4.png)

**Comment by indapublic** [comment]
Demo is working at the moment.
btw demo contains invalid link to old library (`"react-native-view-pdf": "../react-native-view-pdf-0.4.1.tgz"`)

**Comment by sanderfrenken** [comment]
@indapublic can you please confirm the library is linked properly by checking in Xcode under your build's target -> General tab you see the library under the: Linked Frameworks and Libraries section.

In addition, if this does not suffice, you can look under your Build phases tab -> Target Dependencies, and add ReactNativeViewPDF here as well:

<img width="787" alt="screen shot 2018-10-04 at 09 04 35" src="https://user-images.githubusercontent.com/7190049/46458172-319a3d80-c7b5-11e8-9a7e-f97cd23409a4.png">
