### ISSUE TITLE
Open PDF in IOS

### ISSUE THREAD

**Issue by gdierksmeier** [rumax/react-native-PDFView#41]
Sorry, i have a new issue..
I have downloaded a PDF and i need to open it...In Android all OK...but in IOS no way to open the PDF. Well in the emulator is OK, only in real device...Here is the all code..

import React, { Component } from 'react';
import { Alert, WebView, Platform, Share } from "react-native";
import {
  Container,
  Icon,
  Text,
  Content,
  Row,
  ListItem,
  Left,
  Body,
  Button,
  Right,
  View,
  Footer,
  FooterTab
} from "native-base";
import I18n from 'react-native-i18n';
import PDFView from 'react-native-view-pdf';
import PleaseWait from '../../components/PleaseWait/';
import sharedStyles from '../../shared/styles';
import platformStyle from "../../theme/variables/platform";
import generalService from "../../services/general/generalService";
import syncService from "../../services/general/syncService";
import waterfall from "async/waterfall";
import repo from "../../services/database/repository";
// import Spinner from 'react-native-loading-spinner-overlay';
import Spinner from '../../components/Spinner';
import RNFetchBlob from "react-native-fetch-blob";
import Header from '../../components/Header';
import SubHeader from '../../components/SubHeader';
import moment from "moment";

class ViewPDF extends Component {

  constructor( props ) {
    super(props);

    this.state = {
      pdfPath: null
    };

  }

  componentDidMount() {
    let idPaymentForm = repo.configuration.getField('idPaymentForm');
    this.ShowStatementPDF(idPaymentForm);
  }

  ShowStatementPDF( idPaymentForm ) {

    let fs = RNFetchBlob.fs;
    let dirs = fs.dirs;

    const filename = `${idPaymentForm}.pdf`;

    let PDFPath = '';

    if( Platform.OS === 'ios' ) {
      PDFPath = `${dirs.DocumentDir}/${filename}`;
    } else {
      PDFPath = `${dirs.DownloadDir}/${filename}`;
    }

    let DateTo = moment();
    let DateFrom = moment().subtract(90, 'days');
    //TODO , sacar os datos de los parametros... Domain URL + URL API
    //let URL = `https://selfservice.kplc.co.ke/api/balancePdf/2.0.1?fromDate=${DateFrom}&idPaymentForm=${idPaymentForm}&toDate=${DateTo}`;
    let URL = `https://XXXXXXX/api//2.0.1-rn/balancePdf?fromDate=${DateFrom}&idPaymentForm=${idPaymentForm}&toDate=${DateTo}`;

    waterfall([
        ( callback ) => {
          syncService.checkAccesToken(callback);
        },
        ( arg1, callback ) => {

          let access_token = repo.configuration.getField('access_token');

          RNFetchBlob
            .config({
              path: PDFPath,
              fileCache : true,
              appendExt : 'pdf'
            })
            .fetch('GET', URL, {
              'Authorization': 'Bearer ' + access_token,
              'Cache-Control': 'no-store'
            })
            .then(( res ) => {
                return callback(null);
            })
        } ],
      function( err ) {
        if( err ) {
          setTimeout(() => {
            Alert.alert("Data not found", 'Please try again later');
          }, 1000);
        } else {
          this.setState({ pdfPath: PDFPath });
        }
      }.bind(this))

  }

  ShareStatement() {

    let NEW_FILE_PATH = this.state.pdfPath;

    Share.share( {
      message: undefined,
      url: NEW_FILE_PATH,
      title: undefined
    }, {
      // Android only:
      dialogTitle: 'Share the Account Statement',
      // iOS only:
      excludedActivityTypes: [
        'com.apple.UIKit.activity.PostToTwitter'
      ]
    } )

  }

  render() {

      let PDFPath = this.state.pdfPath;
      let resource = "file://" + this.state.pdfPath;
      let resourceType = 'url';

      if (this.state.pdfPath) {

        if (Platform.OS === 'ios') {
          let arr = PDFPath.split('/')
          const dirs = RNFetchBlob.fs.dirs
          PDFPath = `${dirs.DocumentDir}/${arr[arr.length - 1]}`
        }

        return (

          <Container>
            <Header {...this.props} noDrawer
                    iconAction={true}
            />
            <SubHeader text={I18n.t('Statement Preview')} back={true} {...this.props}
                       rightComponent={
                         <Button primary menuSubHeader
                                 onPress={() => this.ShareStatement()}>
                           <Icon name="md-share" style={{ fontSize: 35 }}/>
                         </Button>
                       }/>
              <PDFView style={{ flex: 1, height: platformStyle.deviceHeight }}
                       resource={resource}
                       resourceType={resourceType}
              />
          </Container>
        );
      } else {
        return (
          <Container>
            <Header {...this.props} noDrawer
                    iconAction={true}
            />
            <SubHeader text={I18n.t('Statement Preview')} back={false}/>
            <Content>
              <PleaseWait/>
            </Content>
          </Container>)
      }
    }

//END
}

export default ViewPDF;

**Comment by sanderfrenken** [comment]
Hi there, 

Looks like the same issue as decribed here: #42 

However, do I understand correctly that you are able to load a local pdf file when using the iOS simulator?

**Comment by sanderfrenken** [comment]
Hi again, 

0.3.0 is published with support for loading local files in iOS. 
Please let us know if this works for you.
Android implementation is not yet implemented in the same way, but will be in the foreseeable future.
Be aware you have to use resourceType = file now for iOS when dealing with local files

**Comment by rumax** [comment]
PDF from files was implemented in PR #44 and #43. [NPM package 0.3.1](https://www.npmjs.com/package/react-native-view-pdf) was published. Closing the issue. Please, reopen with additional info if this issue still exists for you.
