### ISSUE TITLE
PDF won't render on real iOS device

### ISSUE THREAD

**Issue by setrin** [rumax/react-native-PDFView#47]
Hello,

Thanks for great work with this library.
However, i have an issue to get PDF rendered on real iPhone. In simulator, everything works great, even on Android simulator/real device. But on real iPhone, i just get blank screen.
I have correct file path, as i'm using localy saved PDF. I have also Share feature, which works correctly with same file path. It seems that the loading of PDF for preview does not start. When i put wrong path, it calls my onError callback, so something is working, but i can't get pdf redered.

Any idea why this might be happening?

Thanks for your replay.
With best regards,
Daniel

**Comment by setrin** [comment]
Hello Sander,

Thanks for your replay. 

Yes, i get that error when i intentionaly screw up the URL.
I tried to debug the native part, and it seems that URL is set correctly. Even webview.isLoading is set to True, so loading starts.

targetUrl is `targetURL	NSURL *	@"file:///var/mobile/Containers/Data/Application/D8A7330D-B891-4C84-99F4-29709E7D0394/Documents/PayoutAssets/bankStatements/statement-12-2017.pdf"	0x00000001d42ae340`

After putting breakpoints to either Finish or Fail callbacks, those are never called, so i guess it's infinitaly loading.

I tried to implement WebView directly from React-Native, and it renders PDF correctly with same URL.

I'm more of a JS developer, so native part is really hard for me to debug and find cause of the problem.
Have you seen something similar to my issue?

Thanks.
Kind regards,

Daniel

**Comment by sanderfrenken** [comment]
Hi Serin,

No Unfortunately I have not, but support for localFile is just recently added so maybe it not used that much yet.

But I think I made a mistake that causes your issue. Maybe you can test it, as I don't have it all at hand right now.
In PDFView.m, can you replace:

```
NSURLRequest *request = [NSURLRequest requestWithURL: targetURL];
[webview loadRequest: request];
```

with:

```
[webview loadFileURL: targetURL allowingReadAccessToURL: targetURL];
```

Rebuild your app afterwards and test the rendering of the PDF. I hope it works, please let me know if it does.

**Comment by setrin** [comment]
Hi Sander,

Yes, this solved my issue.
Thank you very much.

Should i make a pull request, or will you take care of that? I would like to use it as soon as possible without need to edit this each time, as i'm using jenkins and other tools to build the app as well.

Thanks.

**Comment by sanderfrenken** [comment]
That is good to hear! 
No that is for sure, you should not need to edit your the sources your self.
I will patch and create a new version, will let you know when it is available!

Regards,

Sander

**Comment by setrin** [comment]
That would be great :)

Thank you once again.
Regards,

Daniel

**Comment by sanderfrenken** [comment]
Hi Serin,

I just published 0.3.2 to NPM, can you confirm it works correctly OOTB now?

**Comment by setrin** [comment]
Hi Sander,

Wow, that was quick. 
Yes, i can confirm that it works for both Android and iOS.

Thank you.
You can close this issue now

**Comment by sanderfrenken** [comment]
Thnx for your reply, great that it works! 
Good luck with your app :)

**Comment by nirojan0930** [comment]
Actually the problem is caused by the webView.load() function, if we test it on simulators it will work perfectly, but for the real device it may cause some problem and it will not load the webview perfectly. You may check it by calling the didFinish() function. What you need to do is call webView.loadFileURL() rather than webView.load(). It will work in both simulators and real devices. This is very useful when you load any file from local file directory.

**Comment by sanderfrenken** [comment]
Hi nirojan,

I am not really sure what you mean with your comment?
The code has already been changed long ago to use loadFileUrl when the resourceType equals file. 
Is something still not working for you?
