### ISSUE TITLE
minSdkVersion 19

### ISSUE THREAD

**Issue by GantMan** [rumax/react-native-PDFView#49]
### Steps to recreate

open a fresh react-native project.  (0.56 as of this issue).   Install and link the lib.

Get a message that `minSdkVersion` can't be set to 16.

Is this a manual step we need to add to the install readme?

When changing `build.gradle` minSdkVersion to 19 it compiles fine.

**Comment by sanderfrenken** [comment]
Indeed the minSdkVersion when using this library is 19 ( see also here #35).
I will add it to the readme as suggested!

**Comment by rumax** [comment]
@GantMan A new PR was merged https://github.com/rumax/react-native-PDFView/pull/62 which allows to define settings from your project. So if you are still interested, you can try.
