### ISSUE TITLE
Render pdf using {uri,headers} structure?

### ISSUE THREAD

**Issue by indapublic** [rumax/react-native-PDFView#65]
Is it possible to render pdf using {uri,headers} structure?
Like native Image, for example

**Comment by rumax** [comment]
Currently not, but sounds like a good feature! Would you like to create a PR with such changes? Otherwise it can take some time to implement it.

**Comment by rumax** [comment]
Implemented in NPM version 0.5.0

**Comment by indapublic** [comment]
Awesome! @rumax

**Comment by indapublic** [comment]
@rumax Hm. Perhaps I need example how to use headers in your component :)
```
<PDFView
    fadeInDuration={250.0}
    style={{ flex: 1 }}
    resource={{
      uri,
      headers,
    }}
    resourceType="url"
/>
```
`headers` contains only `Authorization` header with `Bearer`

<img width="186" alt="screen shot 2018-10-04 at 17 26 56" src="https://user-images.githubusercontent.com/856260/46458983-e276fb80-c7fa-11e8-91cc-6498e671fee0.png">

<img width="186" alt="screen shot 2018-10-04 at 17 27 06" src="https://user-images.githubusercontent.com/856260/46458987-e3a82880-c7fa-11e8-9bcf-c8489f43cc76.png">

**Comment by indapublic** [comment]
Oh, I got it. Should to use
```
resource={uri}
headers={headers}
resourceType="url"
```

I not see any error on render now, but looks it stucked. I didn't received any events like `onError` or `onLoadComplete`

**Comment by indapublic** [comment]
Oh, nvm. Seems problem related to pdf link
