### ISSUE TITLE
Android: Not able to click on embedded links in PDF

### ISSUE THREAD

**Issue by alexjtark** [rumax/react-native-PDFView#80]
**Describe the bug**
When there is a hyperlink within the pdf, the user cannot click to open it.

**To Reproduce**

- [x] I checked the demo project and cannot reproduce the issue
- [x] I checked the demo project and the issue exists

1. Render PDF
2. click on a link
3. nothing happens

**Expected behavior**
Should open a browser

**Smartphone (please complete the following information):**
 - Device: Android

**Comment by alexjtark** [comment]
@rumax your solution worked out brilliantly. Wasn't aware that the pdfviewer 3.1.0 was beta so i appreciate you helping testing out its stability.

**Comment by rumax** [comment]
@alexjtark Thanks for confirmation. react-native-view-pdf@0.5.6 is published.
