### ISSUE TITLE
Android failure on resolve package

### ISSUE THREAD

**Issue by cybercoder** [rumax/react-native-PDFView#82]
```
Could not find support-v4.jar (com.android.support:support-v4:26.1.0).
  Searched in the following locations:
      https://dl.google.com/dl/android/maven2/com/android/support/support-v4/26.1.0/support-v4-26.1.0.jar
```
This page shows [404](https://dl.google.com/dl/android/maven2/com/android/support/support-v4/26.1.0/support-v4-26.1.0.jar)

**Comment by sanderfrenken** [comment]
This seems to be unrelated to this project, but instead to your gradle/ maven setup, your machine is unable to fetch the Android support libraries. You could check for example here for leads: https://stackoverflow.com/questions/49505245/could-not-find-com-android-tools-buildgradle4-4
