### ISSUE TITLE
Load pdf on ios from assets

### ISSUE THREAD

**Issue by MoudiZd** [rumax/react-native-PDFView#94]
I installed this library in my project to load pdf from assets.

In `android` i tried many tries but in all tries i am encountered by the error `the file not found`

Finally i found the solution by putting the pdf file within `assets` folder in the `res` folder within `src` folder

But in `ios` i was not able to let this works even after doing what is done in the `demo` project by putting the pdf beside the  project folder within `ios` directory neither by putting the file within the bundle beside the `index.js` and `app.js` of my project

Finally i find that putting the file within project folder **beside the `AppDelegate.m`** solve the issue

Hope this info will help someone of you

**Comment by rumax** [comment]
Hi @MoudiZd thanks for using the component and reporting the issue

> In android i tried many tries but in all tries i am encountered by the error the file not found

Can you, please, provide more detailed information like what is the exact `resource` and `resourceType` you used and what is RN version. 

To use the file from the file system on android it should be defined like in demo project: https://github.com/rumax/react-native-PDFView/blob/master/demo/src/resources.js#L19 where you provide full path to the file.

`assets` is also an option, by do not forget that you distribute this file together with the application. Anyway I suggest you to try the [demo project](https://github.com/rumax/react-native-PDFView/tree/master/demo). If you can reproduce the issue there and tell us the steps, it will be posible for us to fix it faster.

In demo project for iOS the downloaded fill will be automatically created (check sources for more information) and on android you need to download some PDF document, call it `downloadedDocument.pdf` and put to downloads folder (the path will be `/sdcard/Download/downloadedDocument.pdf`) or use Device File Explorer in Android Studio to put the file and check the path.

**Comment by MoudiZd** [comment]
Hello @rumax

I use the `resource` file like this 
`resource = "document.pdf";//without situating the relativ path as all my tries failed for that`

And `resourceType` as "file"

The idea  is that my app need to load this pdf file without any need for internet connection

So for that i need that my pdf file reside within my app even their is no internet connection with the user who wants to access my app

Anyway i will try the demo project and will told you how it works with me

Thank you for best regards

**Comment by rumax** [comment]
This is how the path to the file is resolved currently on android:

```
if (filePath.startsWith("/")) { // absolute path, using FS
  input = new FileInputStream(new File(filePath));
} else { // from assets
  AssetManager assetManager = context.getAssets();
  input = assetManager.open(filePath, AssetManager.ACCESS_BUFFER);
}
```

Because you give relative path, assets is used.

Do you mean that you also need something like `/data/user/0/com.demo/YOUR_FILE_NAME.pdf`? If so how do you expect to get the file there? If you download/save it in you app, I think you should know this path, so you can re-use it. Otherwise the file can be stored in assets, which is already supported (both android and iOS).

**Comment by MoudiZd** [comment]
@rumax I am not a good player with native codes

But really what i want is simply a simple way to load `local pdf file` which is found either within bundle beside `index.js` and `App.js` or within app `native resources` inside `res` folder for android or project folder for ios

I think that now the way how it is manipulated it can achieves the loading from `native resources`

But now we want a way to load pdf file from within bundle which is found beside the `index.js` or within any folder beside the `index.js`

Too simply why we must force user to download file when we can put it inside the app like any other local image (Some scenarios may want that , so it must be their a way to implement that without using download at all and just by loading the pdf file from local files for both `android` and `ios` )

Hope my idea is now clear and any clarification needed i am almost ready

**Comment by rumax** [comment]
In demo project you can find `Assets` example, it uses the PDF document that is bundled and you do not need to download it. As far a I understood this is what you need.

**Comment by MoudiZd** [comment]
But trying to put pdf file beside demo project within ios directory does not work for me

Their is any configuration needed to achieve that ??? As only i was able to resolve this by putting the pdf file within demo project beside .h and .m files

Their is anything i am missing about configuring ???

And what about loading file from within bundle like local images (found in the root directory not within platform directories)??

Thank you for all your times you give to reply my questions

**Comment by MoudiZd** [comment]
As you say that i must drag and drop file to the project in xcode and that what i mean by **putting file beside `.m` and `.h` files** as in the demo project this is not done by default and this step (**drag and drop the file into xcode project**) are not mentioned for loading assets in ios or for me at least i have not see it

Now i think the question about

**how to load pdf file from assets** has been answered

And the question remains is can we load a pdf file which is found beside `index.js` if yes ,how ?

**Comment by rumax** [comment]
> And the question remains is can we load a pdf file which is found beside index.js if yes ,how ?

I'm not sure if I understand your question and if it's actually related to the PDF viewer. What is the path to the file? Are you able to access this file from Objective-C or Swift (whatever you use in your project)? If so, can you, please, reproduce this case in demo project and share result, so that we can take a look at this case and possible fix it. Or you can also try to create a Pull Request with a proposal if it's a bug fix or new feature.

**Comment by mamta-deswal** [comment]
I'm using react-native-fs for downloading the pdf and saving it. 

 let url = 'http://samples.leanpub.com/thereactnativebook-sample.pdf';

 const getPdfName = () => {
    return url.split('/').pop();
  };

RNFS.downloadFile({
      fromUrl: url,
      toFile: `${RNFS.DocumentDirectoryPath}/${getPdfName()}`,
    }).promise.then(r => {
      let path = `${RNFS.DocumentDirectoryPath}/${getPdfName()}`;
      setFilePath(path);
    });

const resourceType = 'file';
  const resources = {
   file:  'thereactnativebook-sample.pdf',
  };

return (

   <View style={styles.containerView}>
      <Header
        isBack={true}
        isRightChild={showDownload}
        onDownloadPress={_download}
      />
      <PDFView
        fadeInDuration={250.0}
        style={styles.pdfStyle}
        resource={resources[resourceType]}
        resourceType={resourceType}
        onLoad={() => console.log(`PDF rendered from ${resourceType}`)}
        onError={error => console.log('Cannot render PDF', error)}
      />
    </View>
)

Getting error 'Pdf file not found. While code works fine with URL-type resources.
