### ISSUE TITLE
Multiple pages with different orientation gets stretched on Android

### ISSUE THREAD

**Issue by ymc-thzi** [rumax/react-native-PDFView#96]
Pdf document with multiple pages with different page-orientation the pages gets stretched to the first document orientation on Android.

Render PDF with Android device from this source:
https://www.uster.ch/_docn/1914592/Entsorgungskalender_2019.pdf

**Expected behavior**
Pages keep their aspect ratio

**Screenshots**
<img width="929" alt="bildschirmfoto 2018-12-14 um 10 58 59" src="https://user-images.githubusercontent.com/1804472/49997060-e2c90b00-ff90-11e8-9904-48bf14fdeab3.png">

**Smartphone (please complete the following information):**
 - All Android devices/simulators

**Comment by rumax** [comment]
Hi @ymc-thzi, thank you for using the component and posting the issue. 

On android to display PDF we use `Android PdfViewer` and I see there is still opened issue https://github.com/barteksc/AndroidPdfViewer/issues/213. This could be the reason. 

But I've checked the PDF you provided in demo project and I cannot reproduce the issue with your PDF:

<img width="366" alt="screen shot 2018-12-14 at 20 35 31" src="https://user-images.githubusercontent.com/2707180/50024134-b689aa80-ffe1-11e8-90d1-abd95cb27ec4.png">

<img width="435" alt="screen shot 2018-12-14 at 20 49 46" src="https://user-images.githubusercontent.com/2707180/50024179-dae58700-ffe1-11e8-85c2-c8a7e31dcfa6.png">

The difference in demo project and your project I think is the version of the `Android PdfViewer`. In demo project it is 3.1.0-beta.1. And unfortunately  `Android PdfViewer` is not release with stable version yet. Therefore it was decided to use stable version 2.

Mean time you can try to switch to this version in your app. The way how to do this is in read me and simple:

```
buildscript {
  ext {
    ...
    pdfViewer = "3.1.0-beta.1"
  }
  ...
}
```

Please, let us know if it solves your issue.

**Comment by ymc-thzi** [comment]
@rumax Great, thanks. With using the beta it is working.
