### ISSUE TITLE
OnPageChanged event for IOS

### ISSUE THREAD

**Issue by ShahbazRahmat** [rumax/react-native-PDFView#98]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sanderfrenken** [comment]
Hi @ShahbazRahmat this has been a feature we shortly investigated. 

We would like to add it, but currently we do not have it scheduled to be added by us on the short term.
If you can make a PR with the required changes we will definitely look at it as soon as possible.

Also, for next time please fill in the issue template properly for documentation.

**Comment by rumax** [comment]
Close the issue due to inactivity. In case if this feature is really required, the best option would be to create PR with implementation.
